export const ACTIVITY_TYPES = {
    TASK_CREATE: 'TASK_CREATE',
    TASK_UPDATE: 'TASK_UPDATE',
    TASK_DELETE: 'TASK_DELETE',
    TASK_ASSIGN: 'TASK_ASSIGN',
    TASK_COMPLETE: 'TASK_COMPLETE',
    DISCUSSION_POST: 'DISCUSSION_POST',
    FILE_UPLOAD: 'FILE_UPLOAD',
    SUBMISSION_CREATED: 'SUBMISSION_CREATED',
    SUBMISSION_RESUBMITTED: 'SUBMISSION_RESUBMITTED',
    SUBMISSION_LATE: 'SUBMISSION_LATE',
    REVIEW_SUBMITTED: 'REVIEW_SUBMITTED',
    REVIEW_COMMENT_CREATED: 'REVIEW_COMMENT_CREATED',
    REVIEW_COMMENT_UPDATED: 'REVIEW_COMMENT_UPDATED'
};

export const PAGINATION = {
    DEFAULT_LIMIT: 50,
    MAX_LIMIT: 100,
    MAX_PAGE: 1000
};
