export const ACTIVITY_TYPES = {
    TASK_CREATE: 'TASK_CREATE',
    TASK_UPDATE: 'TASK_UPDATE',
    TASK_DELETE: 'TASK_DELETE',
    TASK_ASSIGN: 'TASK_ASSIGN',
    TASK_COMPLETE: 'TASK_COMPLETE',
    DISCUSSION_POST: 'DISCUSSION_POST',
    FILE_UPLOAD: 'FILE_UPLOAD',
    SUBMISSION_CREATED: 'SUBMISSION_CREATED',
    SUBMISSION_RESUBMITTED: 'SUBMISSION_RESUBMITTED',
    SUBMISSION_LATE: 'SUBMISSION_LATE',
    REVIEW_SUBMITTED: 'REVIEW_SUBMITTED',
    REVIEW_COMMENT_CREATED: 'REVIEW_COMMENT_CREATED',
    REVIEW_COMMENT_UPDATED: 'REVIEW_COMMENT_UPDATED',
    CONTENT_EDITED: 'CONTENT_EDITED'
};

export const PAGINATION = {
    DEFAULT_LIMIT: 50,
    MAX_LIMIT: 100,
    MAX_PAGE: 1000
};

export const CONTRIBUTION_WEIGHTS = {
    [ACTIVITY_TYPES.SUBMISSION_CREATED]: 5,
    [ACTIVITY_TYPES.SUBMISSION_RESUBMITTED]: 3,
    [ACTIVITY_TYPES.SUBMISSION_LATE]: 2,
    [ACTIVITY_TYPES.REVIEW_SUBMITTED]: 4,
    [ACTIVITY_TYPES.TASK_COMPLETE]: 3,
    [ACTIVITY_TYPES.TASK_CREATE]: 1,
    [ACTIVITY_TYPES.TASK_UPDATE]: 1,
    [ACTIVITY_TYPES.DISCUSSION_POST]: 1,
    [ACTIVITY_TYPES.FILE_UPLOAD]: 1,
    [ACTIVITY_TYPES.CONTENT_EDITED]: 2
};

export const CONTRIBUTION_CAPS = {
    [ACTIVITY_TYPES.DISCUSSION_POST]: 5,
    [ACTIVITY_TYPES.FILE_UPLOAD]: 5,
    [ACTIVITY_TYPES.TASK_CREATE]: 10,
    [ACTIVITY_TYPES.TASK_UPDATE]: 10,
    [ACTIVITY_TYPES.CONTENT_EDITED]: 20
};

export const CONTRIBUTION_THRESHOLDS = {
    HIGH: 80,
    NORMAL: 50,
    LOW: 20,
    MIN_RAW_SCORE_FOR_SCALE: 20
};
